---
- name: virtual machines exercise
  hosts: fedora
  gather_facts: false

  vars:
    search_path: /opt
    id: data
    dirs:
      - "/opt/data1"
      - "/opt/data2"
      - "/opt/data3"
    Files: []

  tasks:

    - block:
        - ansible.builtin.wait_for_connection:
            sleep: 1
            timeout: 10
      rescue:
        - ansible.builtin.debug:
            msg: "{{ inventory_hostname }} not connected. End of host."
        - meta: clear_host_errors
        - meta: end_host
    - debug:
        msg: "{{ inventory_hostname }} is running."
    - setup:

    - name: check if directory exists
      ansible.builtin.stat:
        path: "{{ item }}"
      loop: "{{ dirs }}"
      register: result

    - name: check output task above
      ansible.builtin.stat:
        msg: "{{ result }}"

    - name: do something if directory exists
      ansible.builtin.debug: 
        msg: "Directory exists."
      when: (result.stat.isdir is defined) and (result.stat.isdir)

    - name: do something when directory DOES NOT exists
      ansible.builtin.debug: 
        msg: "Directory does not exist."
      when: (result.stat.isdir is undefined) or (not result.stat.isdir)


# trying another method

    - name: Find directory using patterns     # this gives no usefull output, right?
      ansible.builtin.find:
        paths: "{{ search_path }}"
        file_type: directory
        patterns: "{{ dirs }}"
        recurse: yes
      register: found_pattern_matches

    - name: check task above
      ansible.builtin.debug:
        msg: "{{ found_pattern_matches }}"

    - name: msg files attempt
      ansible.builtin.debug:
        msg: "{{ foud_pattern_matches.files }}"


# trying yet another method

    - name: Find files (directories)
      find: 
        paths: "{{ search_path }}"
        file_type: directory
        recurse: no
      register: attempt_3000

    - name: Adding files to the list
      set_fact:
        Files: "{{ Files + [item.path]}}"
      with_items: "{{ attempt_3000.files }}"





  